[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
bytes = "1.4"
serde = { version = "1.0", features = ["derive"] }
